# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='', verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='', verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=datetime.datetime(2017, 4, 24, 2, 37, 47, 221085, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default=''),
        ),
    ]
