# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:05
from __future__ import unicode_literals

import competition.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Competition title')),
                ('content', tinymce.models.HTMLField(verbose_name='Competition content')),
                ('prizes', tinymce.models.HTMLField(verbose_name='Competition prizes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='File name')),
                ('download_count', models.IntegerField(default=0, verbose_name='Counter')),
                ('file', models.FileField(upload_to='dataset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('file', models.FileField(upload_to='submit_file', validators=[competition.utils.FileValidator(content_types=('text/csv', 'text/plain', 'application/vnd.ms-excel'), max_size=102400)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='competition.CompetitionDataset'),
        ),
    ]
