# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiondataset',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='competitiondataset',
            name='file_size',
        ),
        migrations.AddField(
            model_name='competitiondataset',
            name='file',
            field=models.FileField(default=datetime.datetime(2017, 4, 24, 5, 9, 24, 948886, tzinfo=utc), upload_to='dataset'),
            preserve_default=False,
        ),
    ]
