# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmit',
            name='message',
            field=models.CharField(default='', max_length=255, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='competitionsubmit',
            name='status',
            field=models.CharField(default='unknown', max_length=150, verbose_name='Status of submission'),
        ),
    ]
