# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20170424_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='challenge_name',
        ),
    ]
