# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_remove_competition_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='prizes',
            field=models.TextField(default=datetime.datetime(2017, 4, 24, 5, 30, 24, 98272, tzinfo=utc), verbose_name='Competition prizes'),
            preserve_default=False,
        ),
    ]
