# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20170429_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='validate_file',
            field=models.FileField(default='', upload_to='validate_files', verbose_name='Validation file'),
        ),
    ]
