# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competition_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='datasets',
        ),
        migrations.AddField(
            model_name='competition',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, to='competition.CompetitionDataset'),
        ),
    ]
