# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:57
from __future__ import unicode_literals

import competition.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20170429_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='id_col',
            field=models.CharField(default='id', max_length=250, verbose_name='ID column'),
        ),
        migrations.AlterField(
            model_name='competitionsubmit',
            name='file',
            field=models.FileField(upload_to='submit_file', validators=[competition.utils.FileValidator(content_types=('text/csv', 'text/plain', 'application/vnd.ms-excel'), max_size=10485760)]),
        ),
    ]
