# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20170424_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondataset',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
    ]
