# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competitiondataset_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 24, 5, 59, 13, 998059, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitiondataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
