# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20170424_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 15, 38, 6, 498938, tzinfo=utc), verbose_name='Deadline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Competition content'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prizes',
            field=tinymce.models.HTMLField(verbose_name='Competition prizes'),
        ),
    ]
